### ISSUE TITLE
'Sync local activity' for timeline isn't working

### ISSUE THREAD

**Issue by do-not-perceive-me** [toggl/track-macos-feedback#13]
## Summary

- [ ] Crash 
- [x] Glitch 
- [x] Sync 

'Sync local activity' cannot be enabled. 

## Steps to reproduce

https://user-images.githubusercontent.com/109297886/196047797-f4f3bca9-2e15-4151-9f20-d42dff555886.mp4

1. Go to Preferences > Calender
2. Check 'Sync local activity'
3. Close the window or refresh
4. It disables itself

## Expected behavior

It should sync desktop activity and show in the webapp. 

## Affected versions

**App version:** Version 8.2.0 (1815)
**OS version:** macOS Monterey 12.3.1
**Device model:** MacBook Pro (14 inch, 2021, M1 Pro)

**Comment by AndrewVebster** [comment]
Hey, thank you for reporting this. We plan to release a fix this week

**Comment by askrypnyk-toggl** [comment]
Hey @do-not-perceive-me 👋.  

Just to follow-up on this one: we're releasing 8.3.0 this week and the issue should be resolved there.

**Comment by do-not-perceive-me** [comment]
Hello @askrypnyk-toggl! 

Just wanted to confirm that it's working now with the new update :)

**Comment by askrypnyk-toggl** [comment]
Thanks for taking time to confirm, @do-not-perceive-me 🙌
