### ISSUE TITLE
Snap Location and Duration settings are not persisted correctly

### ISSUE THREAD

**Issue by joffotron** [toggl/track-macos-feedback#14]
## Summary
- [ ] Crash 
- [x] Glitch 
- [ ] Sync 

Snap Location and Duration settings are not persisted

## Steps to reproduce

1. Open Preferences
2. Select "1 minute" for "Initial Snap location" and "Snap duration to"
3. Close the preferences window
4. Snapping applies in the app (works okay)
5. Open preferences window again
6. See both settings have reverted back to "15 minutes" :(
7. Snapping behaviour has also now reverted :(

## Expected behavior

The 1 minute snapping behaviour should remain until I deliberately change it

## Affected versions

**App version:** 8.2.0 (1815)
**OS version:** MacOS 12.6
**Device model:** MacBook Pro (13-inch, M1, 2020)

**Comment by askrypnyk-toggl** [comment]
hey @joffotron. thanks for taking your time to send the feedback 🙌.

we're releasing 8.3.0 this week and the issue should no longer be there. please give it a spin when the update reaches you and let us know if did the trick for you.

**Comment by joffotron** [comment]
@askrypnyk-toggl I can confirm this is resolved in 8.3.0 👍🏼
