### ISSUE TITLE
Default project

### ISSUE THREAD

**Issue by wolasss** [toggl/track-macos-feedback#17]
There was an option to set a default project in Toggl Desktop App, so that when I started tracking it automatically selected the default one. 

I can't find that option in the preferences anymore in Toggl Track App. Right now when I start the tracker it goes with "No project".

**App version: 8.3.1
**OS version: MacOS 12.6 (21G115)

**Comment by AndrewVebster** [comment]
Hello 👋 
Thank you for the feedback. We're considering bringing it back.

**Comment by beeradmoore** [comment]
Also wishing of this feature to return.

I just upgraded from the other Github Desktop version to the macOS AppStore version and found this missing. As someone who 95% of the time works on a single project and is required by work to set Toggl projects correctly this was a very useful feature to have.

**Comment by AndrewVebster** [comment]
Closing this issue because in version 8.5.0 this setting is back 🎉
