### ISSUE TITLE
Timer freezes after updating start time

### ISSUE THREAD

**Issue by lukas-zech-software** [toggl/track-macos-feedback#22]
## Summary

- [ ] Crash 
- [x] Glitch 
- [ ] Sync 

When manually correcting the start time of the currently running entry the timer freezes at the current time.
It continues if you click somewhere on the UI outside of the time input, but the timer just skips the time during it was frozen.

The time entry updates to the current time and therefore you not only did not track the time but you also loose the original starting time of the task so you even can't correct it and basically have nothing tracked.

This already caused me to loose multiple hours of tracked time.
## Steps to reproduce

In manual mode:
1. Start a new time entry
2. Click on the timer
3. Select the Start time in the popup
4. Type in some new value e.g. one hour earlier
5. Hit Enter -> popup closes and the timer updates
6. Switch focus to any other window or move the cursor somewhere else
7. The timer is now frozen
8. Wait some time
9. Bring focus back e.g. click the on the App Window
10. The typing cursor appears in the timer input, seems like editing never finished
11. Click somewhere on the window outside the input field
12. Now the timer continues but the time in between is lost
## Expected behavior

After I edit the start time of a running time entry I expect the timer to continue when I leave the app and continue my work.

This was definitely the case in the old version, because I have been doing this for many years
## Affected versions

**App version:** Version 8.5.0 (1948)
**OS version:** 13.0.1 (22A400)
**Device model:** Mac mini M1 (2020) 16GB

**Comment by lukas-zech-software** [comment]
Here's a short video show the issue
![Untitled (1)](https://user-images.githubusercontent.com/10512593/207323388-281144d4-7fa7-42e6-93d1-0e1d0bc8743e.gif)

**Comment by j6k4m8** [comment]
I think the "blur"/lose-focus event is not happening if user cursor leaves the window entirely. I've encountered this a bunch too — very frustrating!

**Comment by lukas-zech-software** [comment]
I agree, it looks like the time is not saved until the focus leaves the
input element, either by clicking somewhere on the rest of the UI or by
hitting Enter a second time.

What makes this so irritating is that until I tried to reproduce the bug, I
didn't even notice that the cursor/focus switches to the time input after I
hit Enter while editing the Start/End time in the little popup.
I am done editing, why would I want the focus to jump to the "main" time
input to continue editing?

But apart from that the timer should probably never not stop, even if an
input currently has the focus. If I click on the input then think about
what I want to edit and after a minute I decide that I actually don't want
to edit anything and just leave the input field again. Even that will cost
me one minute of time that was not tracked!

For me losing tracked time equals losing money so this is very critical to
me and actually made me lose quite a bit of the confidence I had in Toggle
Track for many years now.


Can I switch back to the old version of the app until this is resolved? I
could not find the download for any older version but only the link to the
App Store where only the new version is available

**Comment by AndrewVebster** [comment]
Sorry for the inconvenience. It is a bug, and we're taking it as a high priority, so you can expect to see it fixed in the next update.

Generally, if you focus on the duration text field and then move focus somewhere else, it shows duration correctly. But, unfortunately, it doesn't work as expected after you edit the start time.

If you still want to switch back to the old app, you can write to our support: Main menu -> Help -> Send Feedback.

But I hope once this issue is fixed, you'll try it again and give us your feedback 🙂

**Comment by AndrewVebster** [comment]
@lukas-zech-software @j6k4m8 some improvements were made in the latest version (v8.6.0). We plan to further improve the time editing experience, and we would love to hear your feedback 🙂

**Comment by j6k4m8** [comment]
Excellent, I just confirmed I have 8.6.0 and will report back :)

**Comment by lukas-zech-software** [comment]
@AndrewVebster 
I just tested it with v8.6.0 and it now works as perfectly. The current behaviour is exactly what I would expect and what I was used to from the "old" App.

Thanks for the fast solution!

**Comment by AndrewVebster** [comment]
Thanks for confirming 🙇. Glad our fix helped 🙂 and thanks again for reporting the issue 👍
