### ISSUE TITLE
Laggy timer linting leads to a janky editing experience

### ISSUE THREAD

**Issue by j6k4m8** [toggl/track-macos-feedback#24]
## Summary

- [ ] Crash 
- [x] Glitch 
- [ ] Sync 

Editing time inputboxes has unintuitive and laggy edit validation that can lead to strange behavior.

## Steps to reproduce

I should be able to type any valid time into the timer boxes

## Expected behavior

Some ways of editing text lead to unexpected and unintuitive changes (more details below)

## Affected versions

**App version:** (8.4.0)
**OS version:** MacOS Latest
**Device model:** MacBook Pro Intel

---

#### Example issues
| Action | Expected | Actual |
| --- | --- | --- |
| Change 1:00 to 1:45 | Text changes to 1:45 | If the current time is before 1:45, the text changes to the current time **and the original minute value is lost**. If the current time is after 1:45, the text changes to 1:45 only if the AM/PM selector is compatible. |
| Change AM to PM | AM/PM changes | ...I still haven't figured out the pattern here |
| Press the up/down arrows on a field | Number should increment or decrement by 1 | Number increments or decrements only if it does not violate `start ≤ stop ≤ now`. If any of these are violated, **the edited value "clips" and the original value is lost**. |

See also #22 for related jank!

--- 

Note: I realize that the `start ≤ stop ≤ now` validation makes _sense_, but it is very frustrating to try to type and instead unintuitively modify an unrelated field (i.e., minutes field changes when I update hours).

**Comment by AndrewVebster** [comment]
hey @j6k4m8 👋 Just letting you know that we recently updated the UX for time/duration editing. App version is 8.10.0. I hope the issues you've mentioned are fixed there.

**Comment by j6k4m8** [comment]
Feels a bit glitchy to me still (strange that it changes the date if I type a number larger than the current time before backspacing; now takes two steps to fix) but I agree that this has fixed the issue I reported above! Happy to close this one :) 

PS: I definitely prefer the more-error-prone but way more predictable behavior of the web application, at least for now! I appreciate that's a lot to ask of native UI elements!

**Comment by AndrewVebster** [comment]
Thanks for the feedback 🙌 . There's a chance we'll review the behavior again at some point, but for now I'm glad that it at least fixed some of the issues for you 🙂
