### ISSUE TITLE
Massive input delay while typing the description

### ISSUE THREAD

**Issue by tyrann0us** [toggl/track-macos-feedback#25]
## Summary

- [ ] Crash 
- [x] Glitch 
- [ ] Sync 

Typing in the description field for new entries or when editing existing ones is horribly laggy. There are occasional input delays of up to 1 second.
This seems to be related to Toggle searching for existing entries in the list of suggestions; if I write a "unique" description, it can't match existing entries, and the input delay is relatively small. However, for often-used keywords, the delay increases drastically.

What makes this hard to debug is that the severity of the delay differs randomly. Sometimes, restarting the app significantly improves the situation.

## Steps to reproduce

1. Work on an old laptop
2. Have a lot of existing, often similar entries
3. Start typing a new entry
4. Note a massive input delay

## Expected behavior

No input delay while typing

## Affected versions

**App version:** Version 8.5.0 (1948) from Mac App Store
**OS version:** macOS 11.7.2
**Device model:** MacBook Pro (Retina, 15", Late 2013)

## Additional notes
I planned on providing a screencast but never found the time to do so. I'll try to provide more information later if need be.

**Comment by AndrewVebster** [comment]
@tyrann0us thank you for the feedback and sorry that we are responding just now. Typing performance was improved in 8.7.0. We would love you to try it and get back to us if you still have those issues.

**Comment by tyrann0us** [comment]
Hi @AndrewVebster, thanks for getting back to me.
I can indeed confirm a massive performance improvement in version 8.7.0 (2031). The input delay is down to almost zero.
Thanks for fixing this!
