### ISSUE TITLE
Today's total time not updating while a timer runs

### ISSUE THREAD

**Issue by haukeh** [toggl/track-macos-feedback#26]
## Summary

In the previous macOS App, the "Today" entry was updating its total time while a timer was running. This was very convenient to see on a single glance how much total time was tracked up until now for today. In the new app, the total time ist only updated once a timer is stopped. 

_I don't know if this is an intended change, or a bug. If it is the former, I hope you would consider bringing this feature back._

## Affected versions

**App version: Version 8.5.0 (1948)** 
**OS version: mac OS 13.1**
**Device model: Intel MBP 15" 2018**

**Comment by AndrewVebster** [comment]
Thanks for the feedback 🙌. Currently, we're constrained by some technical limitations, but we'll consider bringing it back (maybe in a slightly different form).

**Comment by AndrewVebster** [comment]
Hey @haukeh 👋 
Just letting you know that in app version 8.10.0 we introduced a new "Today total" header on the List tab. This is only a part of what we plan to display there, but you can already use it 🙂

**Comment by haukeh** [comment]
Hi @AndrewVebster, 

thanks for leeting me know. Looking good! :)
