### ISSUE TITLE
Entering times with a leading zero for the minutes is awkward

### ISSUE THREAD

**Issue by chemicalcrux** [toggl/track-macos-feedback#27]
## Summary
- [ ] Crash 
- [X] Glitch 
- [ ] Sync 

When editing the start and stop times for a task, it's difficult to enter times like 3:02 or 12:07. I have to tab out, rather than just hitting enter.

## Steps to reproduce

1. Start and stop the timer, so that a time entry is created.
2. Edit the time entry
3. Try to set the start or end time's minute section to something like "02"
4. Hit enter
5. The edit menu closes, but nothing changes.

<img width="68" alt="image" src="https://user-images.githubusercontent.com/8015368/210156153-61309d55-36c6-4777-aa83-2373bcad976c.png">

This is what it looks like after typing "02". If I leave it for a few seconds, it does currently turn into "02". If I hit enter before that point, the menu closes without changing the time.

## Expected behavior

Either "02" should appear immediately, or hitting enter should correctly set the time.

## Affected versions

**App version:** 8.5.0 (1948)
**OS version:** 13.0.1 (22A400)
**Device model:** M1 pro macBook, 2021 model.

(small edit: I had an out-of-date client, but the issue remains after updating)

**Comment by AndrewVebster** [comment]
Thanks for reporting this issue 👍. We cannot make "02" it appear immediately, because that's how this default OS control works. It waits if after the number there will be another one.
But we can do "hitting enter should correctly set the time", so you won't need to tab out.

You can expect to see this fix soon. Thanks again for the feedback

**Comment by AndrewVebster** [comment]
The fix was released in version 8.7.0.

> But we can do "hitting enter should correctly set the time", so you won't need to tab out.

**Comment by chemicalcrux** [comment]
Yep, looks like that's fixed now!
