### ISSUE TITLE
Editing dialog - missing option to resize/enlarge the dialog-window

### ISSUE THREAD

**Issue by cyress** [toggl/track-macos-feedback#29]
<img width="295" alt="toggl track - missing resize option" src="https://user-images.githubusercontent.com/363412/210206481-a65cb55f-783d-4b32-adf0-a0def5e90378.png">

## Summary
- [ ] Crash 
- [x] Glitch 
- [ ] Sync 

At the moment it's not possible to enlarge the editing dialog window like in the previous TogglDesktop app.
If you have a some longer description, there is no way to see and edit it completely in the dialog window.

## Steps to reproduce
1. Create a new entry with a longer description.
    * e.g. `An entry with a slightly longer informative description explaining exactly what was done`
2. Open the editing dialog
3. Try to resize/enlarge the editing dialog, so you can see more text.

## Expected behavior
The editing dialog should have a option to resize/enlarge the window horizontally.

## Affected versions
**App version:** 8.5.0
**OS version:** macOS 13.1
**Device model:** MacBook Pro 2016

**Comment by HeRovaZy** [comment]
I have the same issue, but especially with selecting the projects
![Screenshot 2023-01-10 at 10 05 55](https://user-images.githubusercontent.com/14984398/211509396-27d88ec0-8b55-4b95-bcc9-f4f9701e98cb.png)

**Comment by cyress** [comment]
Helllo @AndrewVebster!

I just saw the deprecation message in the previous TogglDesktop app that you implemented.
https://github.com/toggl-open-source/toggldesktop/commit/e1e56f5b430662b663063e2ba5ec8deec0e4bd96

Since the previous app will probably stop working as of 31.01.2023, i wanted to ask if there are any plans to add a resize feature to the edit dialog.
I ask because the small width of the dialog becomes a real problem in everyday usage.

Thanks in advance. ✌️

**Comment by AndrewVebster** [comment]
Thanks for the feedback 🙌. I'll share this feedback with my team and we'll consider adding this feature in one of the future releases.

**Comment by cyress** [comment]
Thanks, that would be awesome. Then I look forward hopefully to the next releases. 😄

**Comment by NickVulkers** [comment]
> Thanks for the feedback 🙌. I'll share this feedback with my team and we'll consider adding this feature in one of the future releases.

Is it still in consideration or a for sure addition? Right now I prefer using 3rd party apps or the web interface...

**Comment by AndrewVebster** [comment]
@NickVulkers, it's at the top of our backlog, so unless we face something unexpected, you can expect to see this feature in the next release or the one after that.

**Comment by tennr** [comment]
Same issue.  This was a major oversight, please include this as a hot fix or don't shutdown the old app until this is added.  For now I'm back to the old app.  Thank you.

**Comment by cyress** [comment]
Hello @AndrewVebster! Do you have any news on this issues?
Now that the previous app no longer works, this bug is one of the problems that are more than just annoying in daily work. 😬

Please adjust this or just let the previous app work a little longer, so that you can fix the last issues in peace. ✌️

**Comment by cyress** [comment]
In the beginning I was relatively hopeful that the last problems of the new app would be solved relatively soon.
One month after my last unanswered query and three months after the initial ticket creation, I am no longer so optimistic.

It wouldn't be so annoying if the previous app would just continue to work until the last issues from the new app were resolved.
But unfortunately there's nothing we can do about that, except hope for the best.

**Comment by askrypnyk-toggl** [comment]
Hey all 👋. 

Sorry for the delay with responding in the thread, it's been a busy couple of weeks 😅. We really appreciate your patience 🙏.

Anyway, we have worked on adjustable edit view width in v8.10.1 that should become available any time now. Could you please check it out and tell us what you think?

**Comment by cyress** [comment]
Hello @askrypnyk-toggl, thank you for your feedback!
The new app version looks very good. And best part is, you can now finally resize the editing dialog.  🎉😄
