### ISSUE TITLE
No timer is shown on menu bar

### ISSUE THREAD

**Issue by EugeneDP89** [toggl/track-macos-feedback#31]
## Summary

- [ ] Crash 
- [ ] Glitch 
- [ ] Sync 

Time in menu bar is not showing

## Steps to reproduce

1. Open app
2. Select "Show timer in menu bar" in General settings
3. Time is not showing, both when task is running and not running (on previous version app icon was shown).

## Expected behavior

App icon is shown when there is no task running, time is shown when task is running

## Affected versions

**App version:*8.6.0* 
**OS version:*Mac OS 13.1*
**Device model:*Macbook Pro 16"*

**Comment by AndrewVebster** [comment]
Thanks for reporting the issue @EugeneDP89 

To make sure I understand the issue: you don't see the Toggl app icon in the menu bar at all, right?

How many applications do you have on the menu bar? Can you remove/close some to ensure you have enough space and try Toggl again? If there is not enough space, macOS will hide icons from the menu bar, so we need to make sure that's not the case here.

**Comment by EugeneDP89** [comment]
@AndrewVebster yes, I don't see icon at all. There is enough space in menu bar, I even tried to close some apps to be sure that it's enough, but no success. With previous version (that will be deprecated at the end of month) there were no such problem.

**Comment by EugeneDP89** [comment]
@AndrewVebster just tried to remove both old and new versions and installed only new one, now it's working and showing both icon and time of started task

**Comment by AndrewVebster** [comment]
I'm glad it now work, because the issue is really strange 🤔. Please let us know if anything like this happens again.
