### ISSUE TITLE
No alarm for the end of pomodoros and breaks

### ISSUE THREAD

**Issue by jimmylad** [toggl/track-macos-feedback#33]
## Summary
In the previous app which is now not supported there was an alarm at the end of pomodoros.

- [ ] Crash 
- [ ] Glitch 
- [ ] Sync 

Is this expected behaviour or a bug?

## Steps to reproduce

Finish a pomodoro and there is no alarm

## Expected behavior

An alarm

## Affected versions

**App version:** 8.6.0
**OS version:** 12.5
**Device model:** Macbook Air M1

**Comment by askrypnyk-toggl** [comment]
Hey @jimmylad 👋, 

Thank you for taking the time to report it 🙌.

The new app uses macOS notifications to bring your attention to Pomodoro events. If you have enabled those in Pomodoro Preferences and you have allowed Toggl Track to display notifications in your macOS preferences (see below), you should see those at the end of each focus and break.

If Notifications are disabled in Pomodoro Preferences (which they are by default), the app is still supposed to playback a short sound at the end of every focus and every break session.

Please let me know if your experience contradicts the above, I'll try to see what might be going wrong.

#### Enabling notifications:
| Toggl Pomodoro Preferences | macOS Ventura Preferences |
|-|-|
| <img width="334" alt="Screenshot 2023-01-27 at 2 13 19 PM" src="https://user-images.githubusercontent.com/108934380/215084895-48c9ea03-7156-423c-b08f-0c17443990c8.png"> | <img width="496" alt="Screenshot 2023-01-27 at 2 09 05 PM" src="https://user-images.githubusercontent.com/108934380/215084929-86f00eba-607e-4b99-b6fc-d660c71dcaf6.png"> |

**Comment by jimmylad** [comment]
Ah OK thanks for you help 👍
