### ISSUE TITLE
Doesn't detect idle state

### ISSUE THREAD

**Issue by andygjp** [toggl/track-macos-feedback#4]
## Summary

- [ ] Crash 
- [ x] Glitch 
- [ ] Sync 

## Steps to reproduce

1. Start tracking some work
2. Leave your computer for over 10 minutes
3. Come back the computer - there is no prompt telling you've been idle for x minutes (like it does on the old app).

## Expected behavior

It should work like version 7.5.441 of the MacOS app, ie display a prompt notifying me I've been idle and ask what I want to do.

## Affected versions

**App version:** 8.0.0 (30)
**OS version:** MacOS 12.4 (21F79)
**Device model:** Mac mini (M1)

**Comment by AndrewVebster** [comment]
Hey @andygjp, thanks for reporting this. Just to make, does you Idle Preferences look like this or do you have a different configuration?
<img width="800" alt="Screenshot 2022-07-13 at 19 55 23" src="https://user-images.githubusercontent.com/3470113/178789022-d5dbf40c-8d22-49be-809a-0140c2e966c6.png">

**Comment by andygjp** [comment]
Hi @AndrewVebster,

My idle preferences look like that.

**Comment by AndrewVebster** [comment]
Okay, thank you. We'll look into that

**Comment by andygjp** [comment]
Got it

![image](https://user-images.githubusercontent.com/1445933/179026905-da9497a3-d1ad-49c1-98a9-6ee9c3210135.png)

1. quit the app
2. turned on notifications
3. started the app
4. started tracking a new task
5. walk away from the computer for 12 minutes

**Comment by andygjp** [comment]
It seems it'll show the prompt once.

I repeated steps 4 and 5 and I didn't get a prompt.

**Comment by AndrewVebster** [comment]
Hey @andygjp thanks for providing more information on this case 🙇. We'll look into that. If we have more question, or you discover anything new, let's be in touch.

**Comment by askrypnyk-toggl** [comment]
Hey @andygjp 👋 , we're working on this issue right now, I caught an edge case and wanted to verify with you if this was similar to what you were experiencing.

When the issue reproduces for you next time, could you please try focusing on the Track window and selecting `Window` > `Bring All to Front` in the menu bar. Will the idle window appear then?

**Comment by andygjp** [comment]
Hi @askrypnyk-toggl ,

In order to speed up testing, I changed the default idle time from 10 minutes to 1 minute and began testing - the idle prompt appeared every time. I changed it back to 10 minutes and repeated my tests and the idle prompt appeared every time.

So far it seems like the issue is fixed.

Did maybe something change in version 8.0.0 (1726)? Is configuring the timeout required?

I'll keep using it in the meantime and let you know if there are any problems.

**Comment by andygjp** [comment]
And I've come back to my machine, after leaving it for a 1.5 hours, and the idle prompt is not there and and selecting `Window > Bring All to Front` doesn't make it appear. So it seems it still doesn't work after all.

**Comment by askrypnyk-toggl** [comment]
Hi @andygjp. Thanks to your feedback I can now rule out the edge case I was worried about 🙇.

Yeah, in my understanding, the actual timeout setting should not matter. 

What might matter is the way time tracking was initiated. Is there a possibility that when the idle detection didn't work for you:
 - you started tracking on another device (or via the web app), or
 - you started it by "resuming" an existing time entry (like on a screenshot below)?
 
<img width="350" alt="Screenshot 2022-08-08 at 7 35 45 AM" src="https://user-images.githubusercontent.com/108934380/183340537-99929a4c-0fd6-423b-ac6d-2d4cc1aa5c13.png">

**Comment by andygjp** [comment]
Hi @askrypnyk-toggl ,

I usually start a timer in the Mac app in one of two ways:

1. Click the Toggl icon in the status menu and click the Continue menu item.
2. Click the Continue button in the app.

I do have the iOS app on my phone, but I only use it to stop a timer if I've left it on for a long time.

**Comment by askrypnyk-toggl** [comment]
Thanks for confirming this, @andygjp 🙇‍♂️. It does sound consistent with what we have observed.
There indeed were issues with Idle detection in case tracking had been started on another device or by "continuing" an existing entry 👀. Good news, we were able to solve them, so this shouldn't occur in the next build. Please stay tuned 📻. If it does, I'll be your person of contact😉.

**Comment by AndrewVebster** [comment]
@andygjp hey 👋
Could you confirm if this issue with Idle detection is fixed for you?

**Comment by andygjp** [comment]
It works for me 👍

**Comment by AndrewVebster** [comment]
Great, I'm glad it helped. I'm closing this issue for now. In case it appears again, please reach out 🙌
