### ISSUE TITLE
The total time for yesterday (and any other day) includes the unfinished time of the timer that is running

### ISSUE THREAD

**Issue by volodymyrpo** [toggl/track-macos-feedback#44]
## Summary

- [ ] Crash 
- [x] Glitch 
- [ ] Sync 

On the calendar, the time for yesterday includes the unfinished time of the tracker that is currently running. This causes the time displayed as yesterday's total to be incorrect.

## Steps to reproduce

1. Trask some time for yesterday.
2. Start tracking for today
3. Open the calendar and select yesterday's calendar
4. See total time updating

https://user-images.githubusercontent.com/97606714/221831647-7cc908c9-a7c3-4a17-a580-ec1fb5dfcbe4.mov

## Expected behavior

The total time on the calendar does not include the tracker time if it is on a different day.

## Affected versions

**App version:** Version 8.9.0 (2066)
**OS version:** 12.6.2 (21G320)
**Device model:** MacBook Pro (16-inch, 2021) Apple M1 Pro

**Comment by AndrewVebster** [comment]
Hey 👋  Thanks for reporting this 🐛. It should be fixed now in version 8.10.0.
