### ISSUE TITLE
High memory consumption

### ISSUE THREAD

**Issue by saibotma** [toggl/track-macos-feedback#56]
## Summary
As visible in the screenshots the app consumes more than 1.5 GB of memory.
I can't reproduce the issue, but the app has been running for a very long time (multple days or even weeks) withoug being closed.

![Screenshot 2023-05-19 at 10 54 12](https://github.com/toggl/track-macos-feedback/assets/26022902/54799750-b294-4242-8d69-a3af8b6d6ac0)
![Screenshot 2023-05-19 at 10 58 04](https://github.com/toggl/track-macos-feedback/assets/26022902/98b52285-2456-4db4-925f-cea1a631b4bb)
![Screenshot 2023-05-19 at 10 58 12](https://github.com/toggl/track-macos-feedback/assets/26022902/3f9a32c2-cb6c-4317-b58c-f5dd28009238)

## Affected versions

**App version:**  8.10.2
**OS version:** 13.2.1
**Device model:** Apple M2 Pro

**Comment by AndrewVebster** [comment]
hey @saibotma 👋 
Sorry for the late reply. Could you please update the app to 8.10.3? There indeed was a memory leak which we already fixed, but seems like your mac didn't update the app automatically.

**Comment by AndrewVebster** [comment]
No problem, tell us if you still see the issue, thanks 🙌
