### ISSUE TITLE
Description breaks into the second line and pushes out the additional information (v8.11.1)

### ISSUE THREAD

**Issue by cyress** [toggl/track-macos-feedback#59]
![toggl-track-description-issue](https://github.com/toggl/track-macos-feedback/assets/363412/e4f7bfde-e5b2-4530-a96b-480d0b7a338c)

## Summary

- [ ] Crash 
- [x] Glitch 
- [ ] Sync 

With the latest update (v.8.11.1), descriptions with a little bit more text break into the second line and push out the additional information as Client, Project and Task.
In addition, the text sometimes run behind the billable icon, depending on the text length and breaks.

## Steps to reproduce

1. Create a new entry with a longer description.
    - e.g. "An entry with a slightly longer informative description explaining exactly what was done"
3. Look at the entry in the overview

## Expected behavior

The time entry should look correct as in the previous version of the app and all information should be visible.

## Affected versions

**App version:** 8.11.1
**OS version:** macOs 13.4
**Device model:** MacBook Pro 16"

**Comment by cyress** [comment]
Hey @AndrewVebster!
After 2.5 weeks without any feedback, i just wanted to ask if you are aware of the display issue or if you don't have this problem?

Thanks! ✌️

**Comment by AndrewVebster** [comment]
@cyress hi 👋 
sorry for the delay, I was sure someone did reply 🙈. Thanks for the ping 🙇. We did fix the issue after you've mentioned it and it will be included in the next release (you'll see it in 1-2 weeks).

And thanks for reporting it 🙌

**Comment by cyress** [comment]
Hey @AndrewVebster,
thanks for your feedback. I am glad that the issue has already been solved. Hopefully the next release won't be too long in coming. 😄

**Comment by electroidru** [comment]
@AndrewVebster @cyress 
Working fine for me after the latest update )
