### ISSUE TITLE
MacOS app keeps closing itself

### ISSUE THREAD

**Issue by HardeepAsrani** [toggl/track-macos-feedback#63]
## Summary

- [x] Crash 
- [ ] Glitch 
- [ ] Sync 

Since the latest update, Toggl closes itself without any error. It just disappears you don't even notice. Many times the timer keeps working when you reopen it.

## Steps to reproduce

Open the app and start a timer, after 20-30 mins, it disappears.

## Expected behavior

To not disappear.

## Affected versions

**App version:** Can't see where to find the version, not in Preference, but it's the latest that I installed today.
**OS version:** 13.4.1
**Device model:** MacBook Air M1

**Comment by arturs105** [comment]
Hey @HardeepAsrani, thanks for the feedback.

You can see the app version by clicking Toggl Track in the macOS menu bar right next to the Apple logo in the top left corner. And then click on "About Toggl Track".

I think there might be a crash happening, but i would need your e-mail address to find that out. Could you send our support team your e-mail either through the macOS app menu bar Help -> Send feedback, or through this link: https://toggl.com/track/contact/. And tell them to forward your e-mail address to Arturs.

A few more questions:
* Do you use any other clients with the same account? For example the web app, browser extensions, mobile app.
* Were you using Pomodoro or just regular time tracking when the app closed itself?
* Are you using Autotracker or Idle detection?

**Comment by HardeepAsrani** [comment]
Hey @arturs105,

I can't get the app version, that menu isn't working, as you can see in the video: https://www.loom.com/share/26851f91c03e40b18ad60c2fb47a31a9

> Do you use any other clients with the same account? For example the web app, browser extensions, mobile app.

Yes, I started to use the Firefox extension just few days back

> Were you using Pomodoro or just regular time tracking when the app closed itself?

Just the normal.

> Are you using Autotracker or Idle detection?

I use the Idle detection and it's been enabled since the beginning.

**Comment by arturs105** [comment]
Hey, thanks for the video. I did some digging and found the reason why your menu bar isn't working. It's the "Show dock icon" setting in Toggl Track preferences General tab. Having it off breaks the menu bar, so turning it back on and closing the window and reopening it should fix it. I've created an issue in our repo for it and i'm talking to the team about scheduling it.

Now back to the original issue. I've received your e-maill address, and i'll look at the crash reports for any crashes from you.

**Comment by HardeepAsrani** [comment]
@arturs105 Just an update, I haven't seen it crashing anymore since yesterday, so might've been some temporary issue. Let me know if you find anything else feel free to close it in case it isn't reproducable.

**Comment by arturs105** [comment]
@HardeepAsrani I'm closing this issue, since it's not crashing for you anymore and i couldn't find any crashes from your account on our analytics tools.

Another user had a similar issue and solved it by backing up and deleting the contents of `~/Library/Keychains` and then restarting the computer. That's something to try if the issue comes back. And if that doesn't fix it, then feel free to reopen this issue.
